# Generated by Django 5.0.1 on 2024-03-27 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact_us', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactus',
            old_name='details',
            new_name='body',
        ),
        migrations.RenameField(
            model_name='contactus',
            old_name='problem',
            new_name='subject',
        ),
    ]
